#!/usr/bin/perl
# Font Zoom Perl Extension

use strict;
use warnings;

my $font = "DejaVu Sans Mono";
# font size in .Xresources is 16
# $fontsize_step * $level should be default font size
my $fontsize_step = 4;
my $level = 4;
my $level_min = 4;

sub on_user_command
{
	my ($self, $cmd) = @_;

	if ($cmd eq "zoom:in") {
		$level++;
	} elsif ($cmd eq "zoom:out") {
		$level-- if $level gt $level_min;
	}

	my $size = $level * $fontsize_step;
	$self->cmd_parse("\033]50;xft:${font}:pixelsize=${size}\007");
}
