# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# vim
alias vi='vim'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'

# map the SSH tunnel user@cite.com to 127.0.0.1:7070
alias proxysite='ssh -f -N -D 7070 user@site.com'

# DNS monitor
alias dnsmonitor='sudo tcpdump -vvv -s 0 -l -n port 53 | egrep --line-buffered -o "(\w|-|\.)+\.(,| )" | tr -d ,'

# earphone line
alias earphone='pactl set-default-sink alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo'

# sshfs CSP home dir
alias cspmount='sshfs user@site.com:/path /mnt/path'
alias cspumount='fusermount -u /mnt/path'

# screen mirror
# alias mirrorscreen='cvlc --avcodec-hw --fb-hw-accel --no-video-deco --no-embedded-video --screen-fps=30 --screen-left=0 --screen-top=0 --screen-width=1920 --screen-height=1080 screen://'
